server:
  port: 9080
  servlet:
    context-path: /api/v1

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/agePers_db
    username: app_user
    password: u$Rpass23
    driver-class-name: org.postgresql.Driver
    platform: postgresql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 9025
