server:
  port: 9080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agePers_db
    username: app_user
    password: u$Rpass23
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        formet_sql: true

  mail:
    host: localhost
    port: 9025
